"""
Calls Claude to generate a structured Salesforce-aware PR review summary
and posts it as a GitHub PR comment via gh CLI.
"""
import json
import os
import subprocess
import sys

import anthropic

SYSTEM_PROMPT = """You are a Salesforce architect reviewing a pull request diff.
Analyse only the changed Apex and LWC code. Respond with a structured markdown comment
that covers:
1. **What changed** — bullet list of affected classes, components, and metadata
2. **Salesforce risks** — governor limits, FLS/sharing violations, bulkification issues,
   missing @AuraEnabled error handling, LWS incompatibilities
3. **Test coverage notes** — new test classes, missing edge cases, bulk test presence
4. **Verdict** — LGTM / Needs changes / Informational

Keep the total response under 600 words. Use markdown formatting suitable for GitHub PR comments."""


def main(diff_file: str) -> None:
    diff = open(diff_file).read()

    if not diff.strip():
        print("Empty diff — skipping AI review")
        return

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ANTHROPIC_API_KEY not set — skipping AI review")
        return

    client = anthropic.Anthropic(api_key=api_key)
    message = client.messages.create(
        model="claude-sonnet-5",
        max_tokens=1024,
        system=SYSTEM_PROMPT,
        messages=[
            {
                "role": "user",
                "content": f"Review this Salesforce diff:\n\n```diff\n{diff[:8000]}\n```",
            }
        ],
    )

    review_body = message.content[0].text
    comment = f"## 🤖 AI Salesforce Review\n\n{review_body}\n\n---\n_Generated by Claude — verify before merging_"

    pr_number = os.environ.get("PR_NUMBER")
    repo = os.environ.get("REPO")
    if pr_number and repo:
        subprocess.run(
            ["gh", "pr", "comment", pr_number, "--body", comment, "--repo", repo],
            check=True,
        )
        print(f"Posted AI review to PR #{pr_number}")
    else:
        print(comment)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <diff-file>")
        sys.exit(1)
    main(sys.argv[1])
